version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
       - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DBInstance.Endpoint.Address}:3306
      WORDPRESS_DB_USER: ${DatabaseUser}
      WORDPRESS_DB_PASSWORD: ${DatabasePassword}
      WORDPRESS_DB_NAME: ${DatabaseName}
    volumes:
      - /var/www/html/:/var/www/html/
